#!/usr/bin/env fish

if not type omf >> /dev/null
    echo "Install omf"
    curl -L https://get.oh-my.fish | fish
end

if not test -d ~/.tmux/plugins/tpm
    echo "Install tmux plugin manager"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
end

if test -z (omf list | grep fzf)
    echo "Install fzf"
    omf install fzf
end

if test -z (omf list | grep bobthefish)
    echo "Install theme"
    omf install bobthefish
end

rsync --exclude ".git/" \
		--exclude "setup" \
		-avh --no-perms . ~;
